name: navigation
publish_to: "none"

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^5.0.4

  welcome:
    path: ../features/welcome
  carousel:
    path: ../features/carousel
  navigation_bar:
    path: ../features/navigation_bar
  influencer:
    path: ../features/influencer
  home:
    path: ../features/home
  contact:
    path: ../features/contact
  about:
    path: ../features/about

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3
  flutter_lints: ^2.0.0
