name: fleeque
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  data:
    path: ./data
  core:
    path: ./core
  core_ui:
    path: ./core_ui/
  domain:
    path: ./domain
  navigation:
    path: ./navigation
  welcome:
    path: ./features/welcome

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
